#!/usr/bin/env bash
#
# Copyright 2020-2023 The WarpX Community
#
# License: BSD-3-Clause-LBNL
# Authors: Axel Huebl

set -eu -o pipefail

cd Docs

curl -L -o amrex-doxygen-web.tag.xml \
  https://amrex-codes.github.io/amrex/docs_xml/doxygen/amrex-doxygen-web.tag.xml

curl -L -o openpmd-api-doxygen-web.tag.xml \
  https://openpmd-api.readthedocs.io/en/latest/_static/doxyhtml/openpmd-api-doxygen-web.tag.xml

# Treat all warnings as errors
if ! grep -q "WARN_AS_ERROR = YES" Doxyfile; then
    # Add line with the comment
    echo "" >> Doxyfile
    echo "# Overwrite value of WARN_AS_ERROR" >> Doxyfile
    echo "WARN_AS_ERROR = YES" >> Doxyfile
fi

# Run doxygen for 1D Cartesian
echo "Analyzing 1D Cartesian..."
echo "" >> Doxyfile
echo "# Overwrite value of PREDEFINED" >> Doxyfile
echo "PREDEFINED += AMREX_SPACEDIM=1 WARPX_DIM_1D_Z=1" >> Doxyfile
doxygen

# Run doxygen for 2D Cartesian
echo "Analyzing 2D Cartesian..."
echo "" >> Doxyfile
echo "# Overwrite value of PREDEFINED" >> Doxyfile
echo "PREDEFINED += AMREX_SPACEDIM=2 WARPX_DIM_XZ=1" >> Doxyfile
doxygen

# Run doxygen for 3D Cartesian
echo "Analyzing 3D Cartesian..."
echo "" >> Doxyfile
echo "# Overwrite value of PREDEFINED" >> Doxyfile
echo "PREDEFINED += AMREX_SPACEDIM=3 WARPX_DIM_3D=1" >> Doxyfile
doxygen

# Run doxygen for 1D cylindrical
echo "Analyzing 1D cylindrical..."
echo "" >> Doxyfile
echo "# Overwrite value of PREDEFINED" >> Doxyfile
echo "PREDEFINED += AMREX_SPACEDIM=1 WARPX_DIM_RCYLINDER=1" >> Doxyfile
doxygen

# Run doxygen for 1D spherical
echo "Analyzing 1D spherical..."
echo "" >> Doxyfile
echo "# Overwrite value of PREDEFINED" >> Doxyfile
echo "PREDEFINED += AMREX_SPACEDIM=1 WARPX_DIM_RSPHERE=1" >> Doxyfile
doxygen
