#!/usr/bin/env python3

# Copyright 2025 Arianna Formenti
#
# This file is part of WarpX.
#
# License: BSD-3-Clause-LBNL

# This tests the loading of an external field from a file
# generated by a previous WarpX simulation.
# This file checks that, at timestep 0,
# the output fields of simulation 1, which are fed as inputs to simulation 2,
# are the same as the output fields of simulation 2.

import numpy as np
from openpmd_viewer import OpenPMDTimeSeries

series1 = OpenPMDTimeSeries(
    "../test_3d_load_external_field_grid_from_another_sim_step1/diags/diag1/"
)
series2 = OpenPMDTimeSeries("diags/fields")

for field in ["E", "B"]:
    for coord in ["x", "y", "z"]:
        f1, info1 = series1.get_field(field=field, coord=coord, iteration=0)
        f2, info2 = series2.get_field(field=field, coord=coord, iteration=0)

        # assert(np.allclose(f1, f2))
        for a in info1.component_attrs:
            assert info1.component_attrs[a] == info2.component_attrs[a]
        for a in info1.field_attrs:
            assert info1.field_attrs[a] == info2.field_attrs[a]

        select = np.s_[2:-2, 2:-2, 2:-2]
        print(np.allclose(f1[select], f2[select], rtol=0.02, atol=0))

do_plot = True
if do_plot:
    Ex1, _ = series1.get_field(field="E", coord="x", iteration=0)
    Ex2, _ = series2.get_field(field="E", coord="x", iteration=0)
    Ey1, _ = series1.get_field(field="E", coord="y", iteration=0)
    Ey2, _ = series2.get_field(field="E", coord="y", iteration=0)
    Ez1, _ = series1.get_field(field="E", coord="z", iteration=0)
    Ez2, _ = series2.get_field(field="E", coord="z", iteration=0)

    Bx1, _ = series1.get_field(field="B", coord="x", iteration=0)
    Bx2, _ = series2.get_field(field="B", coord="x", iteration=0)
    By1, _ = series1.get_field(field="B", coord="y", iteration=0)
    By2, _ = series2.get_field(field="B", coord="y", iteration=0)
    Bz1, _ = series1.get_field(field="B", coord="z", iteration=0)
    Bz2, _ = series2.get_field(field="B", coord="z", iteration=0)

    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(ncols=3, nrows=2, figsize=(6, 6), dpi=300)
    i = j = k = 63  # bad if 0 or -1

    select = np.s_[2:-2]  # bad if : or -1:1 e.g.

    ax[0][0].plot(Ex1[k, j, select], lw=4, label="sim 1")
    ax[0][0].plot(Ex2[k, j, select], lw=2, label="sim 2")
    ax[0][1].plot(Ey1[k, select, i], lw=4)
    ax[0][1].plot(Ey2[k, select, i], lw=2)
    ax[0][2].plot(Ez1[select, j, i], lw=4)
    ax[0][2].plot(Ez2[select, j, i], lw=2)

    ax[1][0].plot(Bx1[k, select, i], lw=4, label="sim 1")
    ax[1][0].plot(Bx2[k, select, i], lw=2, label="sim 2")
    ax[1][1].plot(By1[k, j, select], lw=4)
    ax[1][1].plot(By2[k, j, select], lw=2)
    ax[1][2].plot(Bz1[select, j, i], lw=4)
    ax[1][2].plot(Bz2[select, j, i], lw=2)

    ax[0][0].legend()

    ax[0][0].set_ylabel("$E$ [V/m]")
    ax[1][0].set_ylabel("$B$ [T]")

    ax[0][0].set_title("x")
    ax[0][1].set_title("y")
    ax[0][2].set_title("z")

    ax[1][0].set_xlabel("x [cells]")
    ax[1][1].set_xlabel("y [cells]")
    ax[1][2].set_xlabel("z [cells]")

    fig.tight_layout()
    plt.show()
