name: 🍏 macOS

on:
  workflow_run:
    workflows: [PR analysis]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-macos
  cancel-in-progress: true

jobs:
  build_appleclang:
    uses: ./.github/workflows/macos-shared.yml
