on:
  workflow_call:
    inputs:
      runs-on:
        description: "Type of machine to run on"
        required: true
        type: string
jobs:
  skip_checks:
    name: Skip
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyze PR
        run: |
          .github/workflows/scripts/check_diff.sh     \
            ${{ github.event.pull_request.head.ref }} \
            ${{ github.event.pull_request.base.ref }} \
            ${{ github.event.pull_request.head.repo.clone_url }}
      - name: Debug
        run: echo "env.SKIP_CHECKS=${{ env.SKIP_CHECKS }}"
    outputs:
      skip: ${{ env.SKIP_CHECKS }}
