on:
  workflow_call:
jobs:
  skip_checks:
    name: Skip
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyze PR
        run: |
          .github/workflows/scripts/check_diff.sh     \
            ${{ github.event.pull_request.head.ref }} \
            ${{ github.event.pull_request.base.ref }} \
            ${{ github.event.pull_request.head.repo.clone_url }}
    outputs:
      skip: ${{ env.SKIP_CHECKS }}
